# Generated by Django 3.1.5 on 2021-03-19 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_auto_20210319_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 19, 20, 24, 50, 259018)),
        ),
        migrations.AlterField(
            model_name='student',
            name='ssc_result',
            field=models.FileField(blank=True, default='', upload_to='ssc_results/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
