# Generated by Django 3.1.5 on 2021-03-19 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_auto_20210319_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 19, 20, 25, 58, 873063)),
        ),
        migrations.AlterField(
            model_name='student',
            name='hsc_result',
            field=models.FileField(blank=True, default='', upload_to='hsc_results/'),
        ),
    ]
