# Generated by Django 5.0.7 on 2024-08-04 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_auto_20210407_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 4, 9, 15, 0, 120616)),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2024, 8, 4, 9, 15, 0, 119836)),
        ),
    ]
