# Generated by Django 3.1.5 on 2021-03-19 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_auto_20210319_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 19, 20, 53, 38, 317579)),
        ),
    ]
