# Generated by Django 3.1.5 on 2021-03-19 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0005_auto_20210319_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hsc_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ssc_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 19, 21, 3, 5, 54555)),
        ),
    ]
