# Generated by Django 3.1.5 on 2021-03-19 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0011_auto_20210319_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='sem_1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='marks',
            name='sem_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='marks',
            name='sem_3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='marks',
            name='sem_4',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='marks',
            name='sem_5',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='marks',
            name='sem_6',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='marks',
            name='sem_7',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='marks',
            name='sem_8',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 20, 0, 20, 52, 59651)),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 20, 0, 20, 52, 59651)),
        ),
    ]
