# Generated by Django 3.1.5 on 2021-03-20 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0013_auto_20210320_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=200)),
                ('job_description', models.CharField(default='', max_length=200)),
                ('no_of_vacancies', models.IntegerField()),
                ('url', models.URLField(blank=True)),
                ('file', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 20, 16, 20, 18, 628411)),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 20, 16, 20, 18, 628411)),
        ),
    ]
