# Generated by Django 3.1.5 on 2021-03-20 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0014_auto_20210320_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 20, 16, 23, 39, 602494)),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 20, 16, 23, 39, 602494)),
        ),
    ]
