# Generated by Django 3.1.5 on 2021-03-20 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0016_auto_20210320_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 20, 16, 49, 52, 110869)),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 20, 16, 49, 52, 110869)),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='file',
            field=models.FileField(null=True, upload_to='requirements/'),
        ),
    ]
