# Generated by Django 3.1.5 on 2021-03-21 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0021_auto_20210321_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 21, 13, 53, 0, 541131)),
        ),
        migrations.AlterField(
            model_name='events',
            name='file',
            field=models.FileField(null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 21, 13, 53, 0, 541131)),
        ),
    ]
