# Generated by Django 3.1.5 on 2021-03-21 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0023_auto_20210321_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 21, 15, 35, 26, 882684)),
        ),
        migrations.AlterField(
            model_name='events',
            name='file',
            field=models.ImageField(null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 21, 15, 35, 26, 882684)),
        ),
    ]
