# Generated by Django 3.1.5 on 2021-03-21 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0024_auto_20210321_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 21, 15, 50, 3, 534628)),
        ),
        migrations.AlterField(
            model_name='events',
            name='file',
            field=models.FileField(null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 21, 15, 50, 3, 534628)),
        ),
    ]
