# Generated by Django 3.1.5 on 2021-03-22 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0026_auto_20210321_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 22, 16, 2, 12, 765693)),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 22, 16, 2, 12, 765693)),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(default='H&Y.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
