# Generated by Django 3.1.5 on 2021-03-22 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0027_auto_20210322_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 22, 16, 8, 10, 848023)),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 22, 16, 8, 10, 848023)),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(default='profile_pictures/H&Y.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
