# Generated by Django 3.1.5 on 2021-03-24 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0032_auto_20210324_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_pass_change',
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 24, 15, 7, 13, 269577)),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 24, 15, 7, 13, 269577)),
        ),
    ]
