# Generated by Django 3.1.5 on 2021-03-24 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0033_auto_20210324_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comapnies',
            name='coming_date',
        ),
        migrations.RemoveField(
            model_name='comapnies',
            name='job_description',
        ),
        migrations.AddField(
            model_name='comapnies',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='comapnies',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='comapnies',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='comapnies',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='comapnies',
            name='fb_profile',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='comapnies',
            name='insta_profile',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='comapnies',
            name='linkedin_profile',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='comapnies',
            name='mobile',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='comapnies',
            name='no_of_emplyee',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='comapnies',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='comapnies',
            name='website',
            field=models.URLField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='comapnies',
            name='year_found',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='comapnies',
            name='company_id',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='comapnies',
            name='company_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='comapnies',
            name='field_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 24, 15, 38, 14, 339385)),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 24, 15, 38, 14, 323761)),
        ),
    ]
