# Generated by Django 3.1.5 on 2021-03-24 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0034_auto_20210324_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(editable=False, max_length=255)),
                ('company_username', models.CharField(default='', max_length=100)),
                ('company_name', models.CharField(default='', max_length=100)),
                ('field_name', models.CharField(default='', max_length=100)),
                ('mobile', models.CharField(default='', max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('website', models.URLField(blank=True, default='', max_length=100)),
                ('address', models.TextField(default='')),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('year_found', models.CharField(default='', max_length=6)),
                ('no_of_emplyee', models.CharField(default='', max_length=200)),
                ('fb_profile', models.CharField(default='', max_length=255)),
                ('insta_profile', models.CharField(default='', max_length=255)),
                ('linkedin_profile', models.CharField(default='', max_length=255)),
                ('college_name', models.CharField(default='BVM', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Comapnies',
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 24, 17, 21, 43, 422766)),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 24, 17, 21, 43, 422766)),
        ),
    ]
