# Generated by Django 3.1.5 on 2021-03-24 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0035_auto_20210324_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='no_of_emplyee',
            new_name='no_of_employee',
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 24, 17, 30, 35, 984661)),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 24, 17, 30, 35, 984661)),
        ),
    ]
