# Generated by Django 3.1.5 on 2021-03-24 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0037_auto_20210324_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='hsc_result',
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 24, 18, 35, 46, 55905)),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 24, 18, 35, 46, 55905)),
        ),
        migrations.AlterField(
            model_name='student',
            name='ssc_result',
            field=models.CharField(default='', max_length=20),
        ),
    ]
