# Generated by Django 3.1.5 on 2021-03-24 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0039_auto_20210324_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='hsc_path',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ssc_path',
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 24, 18, 38, 42, 472256)),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 24, 18, 38, 42, 472256)),
        ),
    ]
