# Generated by Django 3.1.5 on 2021-03-24 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0044_auto_20210324_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id_no',
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 24, 18, 49, 55, 8923)),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 24, 18, 49, 55, 8923)),
        ),
    ]
