# Generated by Django 3.1.5 on 2021-03-24 13:22

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0046_auto_20210324_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 24, 18, 52, 15, 86016)),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 24, 18, 52, 15, 86016)),
        ),
        migrations.AlterField(
            model_name='student',
            name='interest',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('wd', 'Web Development'), ('ad', 'App Development'), ('cd', 'Cloud Computing'), ('excel', 'Excel'), ('wp', 'Wordpress'), ('react', 'React'), ('dj', 'Django'), ('bc', 'Block Chain'), ('dm', 'Data Mining'), ('py', 'Python'), ('c', 'C/C++'), ('j', 'Java')], default='', max_length=39),
        ),
    ]
