# Generated by Django 3.1.5 on 2021-03-25 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0049_auto_20210325_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 25, 20, 50, 2, 482183)),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 25, 20, 50, 2, 474259)),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.CharField(default='profile_pictures/H&Y.png', max_length=255, null=True),
        ),
    ]
