# Generated by Django 3.1.5 on 2021-03-27 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0053_auto_20210327_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 27, 14, 45, 35, 225713)),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 27, 14, 45, 35, 225713)),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.TextField(default='H&Y.png', null=True),
        ),
    ]
