# Generated by Django 3.1.5 on 2021-03-27 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0055_auto_20210327_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 27, 16, 30, 5, 974846)),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 27, 16, 30, 5, 974846)),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(default='1', max_length=5),
        ),
    ]
