# Generated by Django 3.1.5 on 2021-03-30 03:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0061_auto_20210330_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 9, 6, 32, 584228)),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 9, 6, 32, 568604)),
        ),
        migrations.AlterField(
            model_name='marks',
            name='first_year',
            field=models.CharField(blank=True, default='0.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='marks',
            name='fourth_year',
            field=models.CharField(blank=True, default='0.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='marks',
            name='second_year',
            field=models.CharField(blank=True, default='0.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='marks',
            name='sem_1',
            field=models.CharField(blank=True, default='0.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='marks',
            name='sem_2',
            field=models.CharField(blank=True, default='0.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='marks',
            name='sem_3',
            field=models.CharField(blank=True, default='0.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='marks',
            name='sem_4',
            field=models.CharField(blank=True, default='0.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='marks',
            name='sem_5',
            field=models.CharField(blank=True, default='0.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='marks',
            name='sem_6',
            field=models.CharField(blank=True, default='0.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='marks',
            name='sem_7',
            field=models.CharField(blank=True, default='0.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='marks',
            name='sem_8',
            field=models.CharField(blank=True, default='0.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='marks',
            name='third_year',
            field=models.CharField(blank=True, default='0.0', max_length=20),
        ),
    ]
