# Generated by Django 3.1.5 on 2021-03-30 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0063_auto_20210330_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='username',
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 10, 3, 7, 484387)),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 10, 3, 7, 484387)),
        ),
    ]
