# Generated by Django 3.1.5 on 2021-03-30 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0066_auto_20210330_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 10, 32, 13, 793954)),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 10, 32, 13, 793954)),
        ),
    ]
