# Generated by Django 3.1.5 on 2021-03-30 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0068_auto_20210330_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(default='', max_length=255, unique=True)),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 11, 36, 37, 171404)),
        ),
        migrations.AlterField(
            model_name='faculties',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 11, 36, 37, 171404)),
        ),
    ]
